# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: "Execução Manual"

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
on:
    workflow_dispatch:
    
#tarefas dentro da pipeline = jobs
jobs:
    #nome do job
    e2e-tests:
        # maquina onde o job vai rodar
        runs-on: [self-hosted, windows]

        # passos do job
        steps:
            # checkout do código
            - uses: actions/checkout@v4

            # limpar ambiente antes de instalar
            - name: Clean workspace
              run: rm -rf node_modules allure-results allure-report

            # instalção do node
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            # instalação do Yarn
            - name: Instalando Yarn
              run: npm install -g yarn
            
            #   instalação das dependências
            - name: Instalando dependências
              run: yarn
            
            # instalação dos Browsers do Playwright
            - name: Instalando Browsers do Playwright
              run: yarn playwright install
            
            # executar os testes e2e
            - name: Executando testes e2e
              run: yarn run e2e

            # instalação do Allure CLI  
            - name: Install Allure CLI
              run: npm install -g allure-commandline

            # verificacao de versao (debug)
            - name: Check Allure version
              run: npx allure --version  

            # irá gerar o relatório do Allure na pipeline
            - name: Generate Allure Report
              run: allure generate allure-results --clean -o allure-report  
            
            # realizar upload do relatório. PS: só consegui abrir o relatório é através do bash: allure open allure-report
            - name: Upload Allure Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: allure-report
                path: allure-report
                retention-days: 7
                
            # Configurar o dorny/test-reporter
            - name: Publicar resultados dos testes
              if: always()
              uses: dorny/test-reporter@v3
              with:
                name: Playwright Tests
                path: results.xml
                reporter: java-junit






